### ISSUE TITLE
fail to reproduce experiment

### ISSUE THREAD

**Issue by LiangSizhe** [RandolphCarter0/TRMUAP#1]
I used the best set-up and ran the code but falied to get such high Attack Success Rates. The ASR of alexnet is 95% but ASR of other models is about 4% lower than the ASR in the paper on average.

**Comment by RandolphCarter0** [comment]
Hi, we update the training strategy to provide a comprehensive illustration of the optimal experiment setup.  You can find the details in README now.

**Comment by LiangSizhe** [comment]
Thanks for your kind reply! The code works well now and our team is planning to further explore df-uap based on your nice work.
